CREATE DATABASE IF NOT EXISTS `demo`;

USE `demo`;

CREATE TABLE IF NOT EXISTS `user`
(
    `id`       BIGINT AUTO_INCREMENT PRIMARY KEY,
    `username` VARCHAR(100) NOT NULL,
    `email`    VARCHAR(100) NULL,
    `password` VARCHAR(100) NOT NULL,
    `role`     TINYINT(1)   NOT NULL DEFAULT 0
);